# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --ignore=E203]
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3.12
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
    -   id: isort
